# EXOPLANETAS, HABITABILIDAD Y LA PARADOJA DE FERMI

Todo esto se encuentra en este [repositorio](https://github.com/urkomen/proyectos/tree/main/The_Bridge/2-EDA)

### Descripción

Voy a realizar un EDA sobre exoplanetas, su habitabilidad y plantear la paradoja de Fermi.
Creo que es un tema que fascina al público general porque conecta directamente con la famosa pregunta:  

“¿Hay vida ahí fuera?”

La clave de este análisis es no hablar de alienígenas ni marcianos, me centraré en los factores 
que afectan a la probabilidad de civilizaciones usando datos astronómicos reales.

Los **exoplanetas** me dan el material empírico: tamaños, temperaturas, distancias, tipos de estrella, zonas habitables. Con la **habitabilidad** definiré criterios cuantitativos: temperatura compatible con agua líquida, tipo de estrella estable, tamaño adecuado, etc. La **Paradoja de Fermi** me proporciona un marco conceptual: si hay tantos planetas potencialmente habitables, ¿por qué no vemos señales de vida inteligente?

Trataré de plantear el proyecto combinando datos, ciencia y filosofía de forma accesible y atractiva.

Hipótesis que tengo en la cabeza:
1. Los métodos actuales detectan preferentemente planetas grandes y calientes, no los más habitables.
2. Las estrellas más estables (actividad baja) tienen más planetas potencialmente habitables.
3. La mayoría de las estrellas cercanas no cumplen simultáneamente condiciones para la vida inteligente (edad, estabilidad, metalicidad, zona habitable,...)
4. La distancia media entre planetas potencialmente habitables es tan grande que la comunicación entre sí o viajes interestelares es muy improbable

Tal vez se me ocurra algo por el camino, pero esta es la idea principal que tengo en estos momentos

Trataré de plantear el proyecto combinando datos, ciencia y filosofía de forma accesible y muy atractiva.

### DATASET

In [1]:
import pandas as pd

Dataset de sistemas planetarios

In [2]:
PSCompPars = pd.read_csv('./data/PSCompPars_2026.03.19_08.41.41.csv') # Ruta lógica desde donde se encuentra el dataset

This file was produced by the [NASA Exoplanet Archive](http://exoplanetarchive.ipac.caltech.edu)
  Thu Mar 19 08:41:59 2026  
El dataset recuperado ha sido el de la tabla [Planetary Systems Composite Data](https://exoplanetarchive.ipac.caltech.edu/cgi-bin/TblView/nph-tblView?app=ExoTbls&config=PSCompPars)

<img src="./img/NASA_PSCompPars.png" width="800" height="400">

Vemos que la propia web de la NASA advierten que estos datos se componen de muchas fuentes. En nuestro caso, no le daremos importancia a esto, ya que no es un estudio formal, sino un análisis para un proyecto personal del curso.

##### COLUMNS  (desplegar solamente bajo tu responsabilidad)

**pl_name**:        Planet Name  
**hostname**:       Host Name  
**pl_letter**:      Planet Letter  
**hd_name**:        HD ID  
**hip_name**:       HIP ID  
**tic_id**:         TIC ID  
**gaia_dr2_id**:    Gaia DR2 ID  
**gaia_dr3_id**:    Gaia DR3 ID  
**sy_snum**:        Number of Stars  
**sy_pnum**:        Number of Planets  
**sy_mnum**:        Number of Moons  
**cb_flag**:        Circumbinary Flag  
**discoverymethod**: Discovery Method  
**disc_year**:      Discovery Year  
**disc_refname**:   Discovery Reference  
**disc_pubdate**:   Discovery Publication Date  
**disc_locale**:    Discovery Locale  
**disc_facility**:  Discovery Facility  
**disc_telescope**: Discovery Telescope  
**disc_instrument**: Discovery Instrument  
**rv_flag**:        Detected by Radial Velocity Variations  
**pul_flag**:       Detected by Pulsar Timing Variations  
**ptv_flag**:       Detected by Pulsation Timing Variations  
**tran_flag**:      Detected by Transits  
**ast_flag**:       Detected by Astrometric Variations  
**obm_flag**:       Detected by Orbital Brightness Modulations  
**micro_flag**:     Detected by Microlensing  
**etv_flag**:       Detected by Eclipse Timing Variations  
**ima_flag**:       Detected by Imaging  
**dkin_flag**:      Detected by Disk Kinematics  
**pl_controv_flag**: Controversial Flag  
**pl_orbper**:      Orbital Period [days]  
**pl_orbpererr1**:  Orbital Period Upper Unc. [days]  
**pl_orbpererr2**:  Orbital Period Lower Unc. [days]  
**pl_orbperlim**:   Orbital Period Limit Flag  
**pl_orbper_reflink**: Orbital Period Reference  
**pl_orbsmax**:     Orbit Semi-Major Axis [au]  
**pl_orbsmaxerr1**: Orbit Semi-Major Axis Upper Unc. [au]  
**pl_orbsmaxerr2**: Orbit Semi-Major Axis Lower Unc. [au]  
**pl_orbsmaxlim**:  Orbit Semi-Major Axis Limit Flag  
**pl_orbsmax_reflink**: Orbit Semi-Major Axis Reference  
**pl_angsep**:      Angular Separation [mas]  
**pl_angseperr1**:  Angular Separation Upper Unc. [mas]  
**pl_angseperr2**:  Angular Separation Lower Unc. [mas]  
**pl_angseplim**:   Angular Separation Limit Flag  
**pl_angsep_reflink**: Angular Separation Reference  
**pl_rade**:        Planet Radius [Earth Radius]  
**pl_radeerr1**:    Planet Radius Upper Unc. [Earth Radius]  
**pl_radeerr2**:    Planet Radius Lower Unc. [Earth Radius]  
**pl_radelim**:     Planet Radius Limit Flag  
**pl_rade_reflink**: Planet Radius Reference  
**pl_radj**:        Planet Radius [Jupiter Radius]  
**pl_radjerr1**:    Planet Radius Upper Unc. [Jupiter Radius]  
**pl_radjerr2**:    Planet Radius Lower Unc. [Jupiter Radius]  
**pl_radjlim**:     Planet Radius Limit Flag  
**pl_radj_reflink**: Planet Radius Reference  
**pl_bmasse**:      Planet Mass or Mass * sin(i) [Earth Mass]  
**pl_bmasseerr1**:  Planet Mass or Mass * sin(i) [Earth Mass] Upper Unc.  
**pl_bmasseerr2**:  Planet Mass or Mass * sin(i) [Earth Mass] Lower Unc.  
**pl_bmasselim**:   Planet Mass or Mass * sin(i) [Earth Mass] Limit Flag  
**pl_bmasse_reflink**: Planet Mass or Mass * sin(i) [Earth Mass] Reference  
**pl_bmassj**:      Planet Mass or Mass * sin(i) [Jupiter Mass]  
**pl_bmassjerr1**:  Planet Mass or Mass * sin(i) [Jupiter Mass] Upper Unc.  
**pl_bmassjerr2**:  Planet Mass or Mass * sin(i) [Jupiter Mass] Lower Unc.  
**pl_bmassjlim**:   Planet Mass or Mass * sin(i) [Jupiter Mass] Limit Flag  
**pl_bmassj_reflink**: Planet Mass or Mass * sin(i) [Jupiter Mass] Reference  
**pl_bmassprov**:   Planet Mass or Mass * sin(i) Provenance  
**pl_dens**:        Planet Density [g/cm3]  
**pl_denserr1**:    Planet Density Upper Unc. [g/cm3]  
**pl_denserr2**:    Planet Density Lower Unc. [g/cm3]  
**pl_denslim**:     Planet Density Limit Flag  
**pl_dens_reflink**: Planet Density Reference  
**pl_orbeccen**:    Eccentricity  
**pl_orbeccenerr1**: Eccentricity Upper Unc.  
**pl_orbeccenerr2**: Eccentricity Lower Unc.  
**pl_orbeccenlim**: Eccentricity Limit Flag  
**pl_orbeccen_reflink**: Eccentricity Reference  
**pl_insol**:       Insolation Flux [Earth Flux]  
**pl_insolerr1**:   Insolation Flux Upper Unc. [Earth Flux]  
**pl_insolerr2**:   Insolation Flux Lower Unc. [Earth Flux]  
**pl_insollim**:    Insolation Flux Limit Flag  
**pl_insol_reflink**: Insolation Flux Reference  
**pl_eqt**:         Equilibrium Temperature [K]  
**pl_eqterr1**:     Equilibrium Temperature Upper Unc. [K]  
**pl_eqterr2**:     Equilibrium Temperature Lower Unc. [K]  
**pl_eqtlim**:      Equilibrium Temperature Limit Flag  
**pl_eqt_reflink**: Equilibrium Temperature Reference  
**pl_orbincl**:     Inclination [deg]  
**pl_orbinclerr1**: Inclination Upper Unc. [deg]  
**pl_orbinclerr2**: Inclination Lower Unc. [deg]  
**pl_orbincllim**:  Inclination Limit Flag  
**pl_orbincl_reflink**: Inclination Reference  
**pl_tranmid**:     Transit Midpoint [days]  
**pl_tranmiderr1**: Transit Midpoint Upper Unc. [days]  
**pl_tranmiderr2**: Transit Midpoint Lower Unc. [days]  
**pl_tranmidlim**:  Transit Midpoint Limit Flag  
**pl_tranmid_systemref**: Transit Midpoint Time Reference Frame and Standard  
**pl_tranmid_reflink**: Time of Conjunction (Transit Midpoint) Reference  
**ttv_flag**:       Data show Transit Timing Variations  
**pl_imppar**:      Impact Parameter  
**pl_impparerr1**:  Impact Parameter Upper Unc.  
**pl_impparerr2**:  Impact Parameter Lower Unc.  
**pl_impparlim**:   Impact Parameter Limit Flag  
**pl_imppar_reflink**: Impact Parameter Reference  
**pl_trandep**:     Transit Depth [%]  
**pl_trandeperr1**: Transit Depth Upper Unc. [%]  
**pl_trandeperr2**: Transit Depth Lower Unc. [%]  
**pl_trandeplim**:  Transit Depth Limit Flag  
**pl_trandep_reflink**: Transit Depth Reference  
**pl_trandur**:     Transit Duration [hours]  
**pl_trandurerr1**: Transit Duration Upper Unc. [hours]  
**pl_trandurerr2**: Transit Duration Lower Unc. [hours]  
**pl_trandurlim**:  Transit Duration Limit Flag  
**pl_trandur_reflink**: Transit Duration Reference  
**pl_ratdor**:      Ratio of Semi-Major Axis to Stellar Radius  
**pl_ratdorerr1**:  Ratio of Semi-Major Axis to Stellar Radius Upper Unc.  
**pl_ratdorerr2**:  Ratio of Semi-Major Axis to Stellar Radius Lower Unc.  
**pl_ratdorlim**:   Ratio of Semi-Major Axis to Stellar Radius Limit Flag  
**pl_ratdor_reflink**: Ratio of Semi-Major Axis to Stellar Radius Reference  
**pl_ratror**:      Ratio of Planet to Stellar Radius  
**pl_ratrorerr1**:  Ratio of Planet to Stellar Radius Upper Unc.  
**pl_ratrorerr2**:  Ratio of Planet to Stellar Radius Lower Unc.  
**pl_ratrorlim**:   Ratio of Planet to Stellar Radius Limit Flag  
**pl_ratror_reflink**: Ratio of Planet to Stellar Radius Reference  
**pl_occdep**:      Occultation Depth [%]  
**pl_occdeperr1**:  Occultation Depth Upper Unc. [%]  
**pl_occdeperr2**:  Occultation Depth Lower Unc. [%]  
**pl_occdeplim**:   Occultation Depth Limit Flag  
**pl_occdep_reflink**: Occultation Depth Reference  
**pl_orbtper**:     Epoch of Periastron [days]  
**pl_orbtpererr1**: Epoch of Periastron Upper Unc. [days]  
**pl_orbtpererr2**: Epoch of Periastron Lower Unc. [days]  
**pl_orbtperlim**:  Epoch of Periastron Limit Flag  
**pl_orbtper_systemref**: Epoco of Periastron Time System Frame and Standard  
**pl_orbtper_reflink**: Epoch of Periastron Reference  
**pl_orblper**:     Argument of Periastron [deg]  
**pl_orblpererr1**: Argument of Periastron Upper Unc. [deg]  
**pl_orblpererr2**: Argument of Periastron Lower Unc. [deg]  
**pl_orblperlim**:  Argument of Periastron Limit Flag  
**pl_orblper_reflink**: Argument of Periastron Reference  
**pl_rvamp**:       Radial Velocity Amplitude [m/s]  
**pl_rvamperr1**:   Radial Velocity Amplitude Upper Unc. [m/s]  
**pl_rvamperr2**:   Radial Velocity Amplitude Lower Unc. [m/s]  
**pl_rvamplim**:    Radial Velocity Amplitude Limit Flag  
**pl_rvamp_reflink**: Radial Velocity Amplitude Reference  
**pl_projobliq**:   Projected Obliquity [deg]  
**pl_projobliqerr1**: Projected Obliquity Upper Unc. [deg]  
**pl_projobliqerr2**: Projected Obliquity Lower Unc. [deg]  
**pl_projobliqlim**: Projected Obliquity Limit Flag  
**pl_projobliq_reflink**: Projected Obliquity Reference  
**pl_trueobliq**:   True Obliquity [deg]  
**pl_trueobliqerr1**: True Obliquity Upper Unc. [deg]  
**pl_trueobliqerr2**: True Obliquity Lower Unc. [deg]  
**pl_trueobliqlim**: True Obliquity Limit Flag  
**pl_trueobliq_reflink**: True Obliquity Reference  
**st_spectype**:    Spectral Type  
**st_spectype_reflink**: Spectral Type Reference  
**st_teff**:        Stellar Effective Temperature [K]  
**st_tefferr1**:    Stellar Effective Temperature Upper Unc. [K]  
**st_tefferr2**:    Stellar Effective Temperature Lower Unc. [K]  
**st_tefflim**:     Stellar Effective Temperature Limit Flag  
**st_teff_reflink**: Stellar Effective Temperature Reference  
**st_rad**:         Stellar Radius [Solar Radius]  
**st_raderr1**:     Stellar Radius Upper Unc. [Solar Radius]  
**st_raderr2**:     Stellar Radius Lower Unc. [Solar Radius]  
**st_radlim**:      Stellar Radius Limit Flag  
**st_rad_reflink**: Stellar Radius Reference  
**st_mass**:        Stellar Mass [Solar mass]  
**st_masserr1**:    Stellar Mass Upper Unc. [Solar mass]  
**st_masserr2**:    Stellar Mass Lower Unc. [Solar mass]  
**st_masslim**:     Stellar Mass Limit Flag  
**st_mass_reflink**: Stellar Mass Reference  
**st_met**:         Stellar Metallicity [dex]  
**st_meterr1**:     Stellar Metallicity Upper Unc. [dex]  
**st_meterr2**:     Stellar Metallicity Lower Unc. [dex]  
**st_metlim**:      Stellar Metallicity Limit Flag  
**st_met_reflink**: Stellar Metallicity Reference  
**st_metratio**:    Stellar Metallicity Ratio  
**st_lum**:         Stellar Luminosity [log(Solar)]  
**st_lumerr1**:     Stellar Luminosity Upper Unc. [log(Solar)]  
**st_lumerr2**:     Stellar Luminosity Lower Unc. [log(Solar)]  
**st_lumlim**:      Stellar Luminosity Limit Flag  
**st_lum_reflink**: Stellar Luminosity Reference  
**st_logg**:        Stellar Surface Gravity [log10(cm/s2)]  
**st_loggerr1**:    Stellar Surface Gravity Upper Unc. [log10(cm/s2)]  
**st_loggerr2**:    Stellar Surface Gravity Lower Unc. [log10(cm/s2)]  
**st_logglim**:     Stellar Surface Gravity Limit Flag  
**st_logg_reflink**: Stellar Surface Gravity Reference  
**st_age**:         Stellar Age [Gyr]  
**st_ageerr1**:     Stellar Age Upper Unc. [Gyr]  
**st_ageerr2**:     Stellar Age Lower Unc. [Gyr]  
**st_agelim**:      Stellar Age Limit Flag  
**st_age_reflink**: Stellar Age Reference  
**st_dens**:        Stellar Density [g/cm3]  
**st_denserr1**:    Stellar Density Upper Unc. [g/cm3]  
**st_denserr2**:    Stellar Density Lower Unc. [g/cm3]  
**st_denslim**:     Stellar Density Limit Flag  
**st_dens_reflink**: Stellar Density Reference  
**st_vsin**:        Stellar Rotational Velocity [km/s]  
**st_vsinerr1**:    Stellar Rotational Velocity [km/s] Upper Unc.  
**st_vsinerr2**:    Stellar Rotational Velocity [km/s] Lower Unc.  
**st_vsinlim**:     Stellar Rotational Velocity Limit Flag  
**st_vsin_reflink**: Stellar Rotational Velocity Reference  
**st_rotp**:        Stellar Rotational Period [days]  
**st_rotperr1**:    Stellar Rotational Period [days] Upper Unc.  
**st_rotperr2**:    Stellar Rotational Period [days] Lower Unc.  
**st_rotplim**:     Stellar Rotational Period Limit Flag  
**st_rotp_reflink**: Stellar Rotational Period Reference  
**st_radv**:        Systemic Radial Velocity [km/s]  
**st_radverr1**:    Systemic Radial Velocity Upper Unc. [km/s]  
**st_radverr2**:    Systemic Radial Velocity Lower Unc. [km/s]  
**st_radvlim**:     Systemic Radial Velocity Limit Flag  
**st_radv_reflink**: Systemic Radial Velocity Reference  
**rastr**:          RA [sexagesimal]  
**ra**:             RA [deg]  
**decstr**:         Dec [sexagesimal]  
**dec**:            Dec [deg]  
**glat**:           Galactic Latitude [deg]  
**glon**:           Galactic Longitude [deg]  
**elat**:           Ecliptic Latitude [deg]  
**elon**:           Ecliptic Longitude [deg]  
**ra_reflink**:     Position Reference  
**sy_pm**:          Total Proper Motion [mas/yr]  
**sy_pmerr1**:      Total Proper Motion Upper Unc [mas/yr]  
**sy_pmerr2**:      Total Proper Motion Lower Unc [mas/yr]  
**sy_pmra**:        Proper Motion (RA) [mas/yr]  
**sy_pmraerr1**:    Proper Motion (RA) [mas/yr] Upper Unc  
**sy_pmraerr2**:    Proper Motion (RA) [mas/yr] Lower Unc  
**sy_pmdec**:       Proper Motion (Dec) [mas/yr]  
**sy_pmdecerr1**:   Proper Motion (Dec) [mas/yr] Upper Unc  
**sy_pmdecerr2**:   Proper Motion (Dec) [mas/yr] Lower Unc  
**sy_pm_reflink**:  Proper Motion Reference  
**sy_dist**:        Distance [pc]  
**sy_disterr1**:    Distance [pc] Upper Unc  
**sy_disterr2**:    Distance [pc] Lower Unc  
**sy_dist_reflink**: Distance Reference  
**sy_plx**:         Parallax [mas]  
**sy_plxerr1**:     Parallax [mas] Upper Unc  
**sy_plxerr2**:     Parallax [mas] Lower Unc  
**sy_plx_reflink**: Parallax Reference  
**sy_bmag**:        B (Johnson) Magnitude  
**sy_bmagerr1**:    B (Johnson) Magnitude Upper Unc  
**sy_bmagerr2**:    B (Johnson) Magnitude Lower Unc  
**sy_bmag_reflink**: B (Johnson) Magnitude Reference  
**sy_vmag**:        V (Johnson) Magnitude  
**sy_vmagerr1**:    V (Johnson) Magnitude Upper Unc  
**sy_vmagerr2**:    V (Johnson) Magnitude Lower Unc  
**sy_vmag_reflink**: V (Johnson) Magnitude Reference  
**sy_jmag**:        J (2MASS) Magnitude  
**sy_jmagerr1**:    J (2MASS) Magnitude Upper Unc  
**sy_jmagerr2**:    J (2MASS) Magnitude Lower Unc  
**sy_jmag_reflink**: J (2MASS) Magnitude Reference  
**sy_hmag**:        H (2MASS) Magnitude  
**sy_hmagerr1**:    H (2MASS) Magnitude Upper Unc  
**sy_hmagerr2**:    H (2MASS) Magnitude Lower Unc  
**sy_hmag_reflink**: H (2MASS) Magnitude Reference  
**sy_kmag**:        Ks (2MASS) Magnitude  
**sy_kmagerr1**:    Ks (2MASS) Magnitude Upper Unc  
**sy_kmagerr2**:    Ks (2MASS) Magnitude Lower Unc  
**sy_kmag_reflink**: Ks (2MASS) Magnitude Reference  
**sy_umag**:        u (Sloan) Magnitude  
**sy_umagerr1**:    u (Sloan) Magnitude Upper Unc  
**sy_umagerr2**:    u (Sloan) Magnitude Lower Unc  
**sy_umag_reflink**: u (Sloan) Magnitude Reference  
**sy_gmag**:        g (Sloan) Magnitude  
**sy_gmagerr1**:    g (Sloan) Magnitude Upper Unc  
**sy_gmagerr2**:    g (Sloan) Magnitude Lower Unc  
**sy_gmag_reflink**: g (Sloan) Magnitude Reference  
**sy_rmag**:        r (Sloan) Magnitude  
**sy_rmagerr1**:    r (Sloan) Magnitude Upper Unc  
**sy_rmagerr2**:    r (Sloan) Magnitude Lower Unc  
**sy_rmag_reflink**: r (Sloan) Magnitude Reference  
**sy_imag**:        i (Sloan) Magnitude  
**sy_imagerr1**:    i (Sloan) Magnitude Upper Unc  
**sy_imagerr2**:    i (Sloan) Magnitude Lower Unc  
**sy_imag_reflink**: i (Sloan) Magnitude Reference  
**sy_zmag**:        z (Sloan) Magnitude  
**sy_zmagerr1**:    z (Sloan) Magnitude Upper Unc  
**sy_zmagerr2**:    z (Sloan) Magnitude Lower Unc  
**sy_zmag_reflink**: z (Sloan) Magnitude Reference  
**sy_w1mag**:       W1 (WISE) Magnitude  
**sy_w1magerr1**:   W1 (WISE) Magnitude Upper Unc  
**sy_w1magerr2**:   W1 (WISE) Magnitude Lower Unc  
**sy_w1mag_reflink**: W1 (WISE) Magnitude Reference  
**sy_w2mag**:       W2 (WISE) Magnitude  
**sy_w2magerr1**:   W2 (WISE) Magnitude Upper Unc  
**sy_w2magerr2**:   W2 (WISE) Magnitude Lower Unc  
**sy_w2mag_reflink**: W2 (WISE) Magnitude Reference  
**sy_w3mag**:       W3 (WISE) Magnitude  
**sy_w3magerr1**:   W3 (WISE) Magnitude Upper Unc  
**sy_w3magerr2**:   W3 (WISE) Magnitude Lower Unc  
**sy_w3mag_reflink**: W3 (WISE) Magnitude Reference  
**sy_w4mag**:       W4 (WISE) Magnitude  
**sy_w4magerr1**:   W4 (WISE) Magnitude Upper Unc  
**sy_w4magerr2**:   W4 (WISE) Magnitude Lower Unc  
**sy_w4mag_reflink**: W4 (WISE) Magnitude Reference  
**sy_gaiamag**:     Gaia Magnitude  
**sy_gaiamagerr1**: Gaia Magnitude Upper Unc  
**sy_gaiamagerr2**: Gaia Magnitude Lower Unc  
**sy_gaiamag_reflink**: Gaia Magnitude Reference  
**sy_icmag**:       I (Cousins) Magnitude  
**sy_icmagerr1**:   I (Cousins) Magnitude Upper Unc  
**sy_icmagerr2**:   I (Cousins) Magnitude Lower Unc  
**sy_icmag_reflink**: I (Cousins) Magnitude Reference  
**sy_tmag**:        TESS Magnitude  
**sy_tmagerr1**:    TESS Magnitude Upper Unc  
**sy_tmagerr2**:    TESS Magnitude Lower Unc  
**sy_tmag_reflink**: TESS Magnitude Reference  
**sy_kepmag**:      Kepler Magnitude  
**sy_kepmagerr1**:  Kepler Magnitude Upper Unc  
**sy_kepmagerr2**:  Kepler Magnitude Lower Unc  
**sy_kepmag_reflink**: Kepler Magnitude Reference  
**pl_nnotes**:      Number of Notes  
**st_nphot**:       Number of Photometry Time Series  
**st_nrvc**:        Number of Radial Velocity Time Series  
**st_nspec**:       Number of Stellar Spectra Measurements  
**pl_nespec**:      Number of Eclipse Spectra  
**pl_ntranspec**:   Number of Transmission Spectra  
**pl_ndispec**:     Number of Direct Imaging Spectra

### Análisis inicial

Vemos que vienen muchísimos más datos de los que necesitamos. Existe una versión con menos columnas, pero debido a que hay algún dato que necesitamos que no está en esa versión reducida, debemos partir de este dataset completo.

Para nuestro análisis exploratorio necesitaremos los siguientes datos (* datos imprescindibles):

<u>Planeta</u>  
- (*)radio en radios terrestres
- (*)masa en masas terrestres
- (*)temperatura de equilibrio
- periodo orbital
- semieje mayor (distancia a la estrella)
- insolación recibida
- (*)indicador de zona habitable (si no está, se calcula)

<u>Estrella</u>  
- temperatura efectiva
- radio
- masa
- (*)metalicidad
- (*)tipo de estrella/tipo espectral (G, K, M…)
- (*)edad estimada

<u>Sistema</u>  
- (*)distancia en parsecs
- número de planetas en el sistema
- (*)método de detección

Echamos un primer vistazo a los datos:

In [3]:
PSCompPars.head()

,loc_rowid,pl_name,hostname,sy_snum,sy_pnum,discoverymethod,disc_year,disc_facility,pl_controv_flag,pl_orbper,...,sy_disterr2,sy_vmag,sy_vmagerr1,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2
0,1,11 Com b,11 Com,2,1,Radial Velocity,2007.0,Xinglong Station,0,323.21000,...,-1.9238,4.72307,0.023,-0.023,2.282,0.346,-0.346,4.44038,0.003848,-0.003848
1,2,11 UMi b,11 UMi,1,1,Radial Velocity,2009.0,Thueringer Landessternwarte Tautenburg,0,516.21997,...,-1.9765,5.01300,0.005,-0.005,1.939,0.270,-0.270,4.56216,0.003903,-0.003903
2,3,14 And b,14 And,1,1,Radial Velocity,2008.0,Okayama Astrophysical Observatory,0,186.76000,...,-0.7140,5.23133,0.023,-0.023,2.331,0.240,-0.240,4.91781,0.002826,-0.002826
3,4,14 Her b,14 Her,1,2,Radial Velocity,2002.0,W. M. Keck Observatory,0,1765.03890,...,-0.0073,6.61935,0.023,-0.023,4.714,0.016,-0.016,6.38300,0.000351,-0.000351
4,5,16 Cyg B b,16 Cyg B,3,1,Radial Velocity,1996.0,Multiple Observatories,0,798.50000,...,-0.0111,6.21500,0.016,-0.016,4.651,0.016,-0.016,6.06428,0.000603,-0.000603

In [ ]:
# Dimensiones del df (filas x columnas)
PSCompPars.shape

(6147, 85)

In [5]:
# Información sobre columnas
PSCompPars.describe().T

,count,mean,std,min,25%,50%,75%,max
loc_rowid,6147.0,3074.000000,1774.630384,1.000000,1537.500000,3074.000000,4610.500000,6147.000000
sy_snum,6147.0,1.103628,0.342981,1.000000,1.000000,1.000000,1.000000,4.000000
sy_pnum,6147.0,1.774687,1.158518,1.000000,1.000000,1.000000,2.000000,8.000000
disc_year,6146.0,2016.981939,4.962135,1992.000000,2014.000000,2016.000000,2021.000000,2026.000000
pl_controv_flag,6147.0,0.007971,0.088933,0.000000,0.000000,0.000000,0.000000,1.000000
...,...,...,...,...,...,...,...,...
sy_kmagerr1,5828.0,0.041517,0.253471,0.011000,0.020000,0.023000,0.031000,9.995000
sy_kmagerr2,5817.0,-0.041532,0.259355,-9.995000,-0.031000,-0.023000,-0.020000,-0.011000
sy_gaiamag,5809.0,12.253279,2.962278,2.364310,10.356000,12.968200,14.679900,20.186100
sy_gaiamagerr1,5809.0,0.000644,0.001807,0.000112,0.000257,0.000364,0.000543,0.063232
sy_gaiamagerr2,5809.0,-0.000644,0.001807,-0.063232,-0.000543,-0.000364,-0.000257,-0.000112

In [6]:
# Hay valores nulos?
PSCompPars.info()

<class 'pandas.DataFrame'>
RangeIndex: 6147 entries, 0 to 6146
Data columns (total 85 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   loc_rowid        6147 non-null   int64
 1   pl_name          6147 non-null   str
 2   hostname         6147 non-null   str
 3   sy_snum          6147 non-null   int64
 4   sy_pnum          6147 non-null   int64
 5   discoverymethod  6147 non-null   str
 6   disc_year        6146 non-null   float64
 7   disc_facility    6147 non-null   str
 8   pl_controv_flag  6147 non-null   int64
 9   pl_orbper        5814 non-null   float64
 10  pl_orbpererr1    5322 non-null   float64
 11  pl_orbpererr2    5322 non-null   float64
 12  pl_orbperlim     5814 non-null   float64
 13  pl_orbsmax       5831 non-null   float64
 14  pl_orbsmaxerr1   3892 non-null   float64
 15  pl_orbsmaxerr2   3892 non-null   float64
 16  pl_orbsmaxlim    5832 non-null   float64
 17  pl_rade          6097 non-null   float64
 18  pl_radeerr1      4216 non-null   float64
 19  pl_radeerr2      4216 non-null   float64
 20  pl_radelim       6097 non-null   float64
 21  pl_radj          6097 non-null   float64
 22  pl_radjerr1      4216 non-null   float64
 23  pl_radjerr2      4216 non-null   float64
 24  pl_radjlim       6097 non-null   float64
 25  pl_bmasse        6116 non-null   float64
 26  pl_bmasseerr1    2981 non-null   float64
 27  pl_bmasseerr2    2981 non-null   float64
 28  pl_bmasselim     6116 non-null   float64
 29  pl_bmassj        6116 non-null   float64
 30  pl_bmassjerr1    2981 non-null   float64
 31  pl_bmassjerr2    2981 non-null   float64
 32  pl_bmassjlim     6116 non-null   float64
 33  pl_bmassprov     6147 non-null   str
 34  pl_orbeccen      5211 non-null   float64
 35  pl_orbeccenerr1  1857 non-null   float64
 36  pl_orbeccenerr2  1857 non-null   float64
 37  pl_orbeccenlim   5211 non-null   float64
 38  pl_insol         4308 non-null   float64
 39  pl_insolerr1     3628 non-null   float64
 40  pl_insolerr2     3628 non-null   float64
 41  pl_insollim      4308 non-null   float64
 42  pl_eqt           4585 non-null   float64
 43  pl_eqterr1       1803 non-null   float64
 44  pl_eqterr2       1803 non-null   float64
 45  pl_eqtlim        4585 non-null   float64
 46  ttv_flag         6147 non-null   int64
 47  st_spectype      2298 non-null   str
 48  st_teff          5858 non-null   float64
 49  st_tefferr1      5657 non-null   float64
 50  st_tefferr2      5657 non-null   float64
 51  st_tefflim       5858 non-null   float64
 52  st_rad           5834 non-null   float64
 53  st_raderr1       5675 non-null   float64
 54  st_raderr2       5674 non-null   float64
 55  st_radlim        5834 non-null   float64
 56  st_mass          6139 non-null   float64
 57  st_masserr1      5869 non-null   float64
 58  st_masserr2      5868 non-null   float64
 59  st_masslim       6139 non-null   float64
 60  st_met           5595 non-null   float64
 61  st_meterr1       5311 non-null   float64
 62  st_meterr2       5311 non-null   float64
 63  st_metlim        5595 non-null   float64
 64  st_metratio      5577 non-null   str
 65  st_logg          5830 non-null   float64
 66  st_loggerr1      5651 non-null   float64
 67  st_loggerr2      5651 non-null   float64
 68  st_logglim       5830 non-null   float64
 69  rastr            6147 non-null   str
 70  ra               6147 non-null   float64
 71  decstr           6147 non-null   str
 72  dec              6147 non-null   float64
 73  sy_dist          6120 non-null   float64
 74  sy_disterr1      6013 non-null   float64
 75  sy_disterr2      6013 non-null   float64
 76  sy_vmag          5853 non-null   float64
 77  sy_vmagerr1      5845 non-null   float64
 78  sy_vmagerr2      5840 non-null   float64
 79  sy_kmag          5865 non-null   float64
 80  sy_kmagerr1      5828 non-null   float64
 81  sy_kmagerr2      5817 non-null   float64
 82  sy_gaiamag       5809 non-null   float64
 83  sy_gaiamagerr1   5809 non-null   float64
 84  sy_gaiamagerr2   5809 non-null   float64
dtypes: float64(71), int64(5), str(9)
memory usage: 4.0 MB

In [7]:
# Valores diferentes
PSCompPars.nunique()

loc_rowid         6147
pl_name           6147
hostname          4579
sy_snum              4
sy_pnum              8
                  ...
sy_kmagerr1        158
sy_kmagerr2        157
sy_gaiamag        4156
sy_gaiamagerr1    1129
sy_gaiamagerr2    1129
Length: 85, dtype: int64